apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-grafana
spec:
  storageClassName: sc-cinder
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
      # persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data2"
