apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  storageClassName: sc-cinder
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
      # persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"
