apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-data-dir-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-cinder



