apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  nginx.conf: |
    events {
      worker_connections  4096;
    }
    http {
      server {
        listen 80;
        location /app1/ {
          proxy_pass http://app1/;
        }
        location /app2/ {
          proxy_pass http://app2/;
        }
      }
    }
