apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://mydata;  #  any traffic at root location of myweb server, will be forward to http://mydata
        proxy_http_version 1.1;
      }
    }


