apiVersion: v1

kind: Service

metadata:

  name: nagios-service
  namespace: nagios

spec:

  type: NodePort

  selector:

    app: nagios-core

  ports:

    - port: 80

      targetPort: 80

      nodePort: 30008
