
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      containers:
      - image: mahfuzrubel0660/app1:1
        name: app1
        resources: {}
      nodeSelector:
        kubernetes.io/hostname: worker1
status: {}
