
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: kubernetes-dashboard
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: dashboard-admin
  namespace: kubernetes-dashboard

roleRef:
  kind: Role
  name: pod-dashboard
  apiGroup: rbac.authorization.k8s.io

