
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2
    spec:
      containers:
      - image: mahfuzrubel0660/app2:1
        name: app2
        resources: {}
      nodeSelector:
        kubernetes.io/hostname: worker2

status: {}
