apiVersion: v1
kind: ConfigMap
metadata:
  name: index-configmap
data:
  index.html: |
    <body bgcolor="green">
      <center>
        <h1><front color="yellow">Hello I am App-1</front></h1>
      </center>
    </body>
