
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      containers:
      - image: mahfuzrubel0660/app1:1
        name: app1
        resources: {}
        #        volumeMounts:
        #- name: index-configmap
        #  mountPath: /usr/share/nginx/html/
        #ports:
        #- containerPort: 80
        # volumes:
        #        - name: index-configmap
        #  configMap:
        #    name: index-configmap
        #      nodeSelector:
        #kubernetes.io/hostname: worker01

status: {}
